$CERTCLIBSrc = @"

using System;
namespace CERTCLILib
{
	public enum X509EnrollmentAuthFlags
	{
		X509AuthNone,
		X509AuthAnonymous,
		X509AuthKerberos,
		X509AuthUsername = 4,
		X509AuthCertificate = 8
	}


    public enum ConfigFlags
    {
        DefaultConfig = 0,
        UIPickConfig = 0x1
    }

    public enum CertRequestFormat
    {
        Base64 = 0x1,
        FormatAny = 0,
        PKCS10 = 0x100
    }

    public enum CertDisposition
    {
        Issued = 0x3,
        UnderSubmission = 0x5
    }

    public enum CertOutput
    {
        Base64 = 0x1,
        Chain = 0x100
    }
}
"@



$CERTENROLLibSrc = @"

using System;
namespace CERTENROLLLib
{
	public enum AlgorithmFlags
	{
		AlgorithmFlagsNone,
		AlgorithmFlagsWrap
	}
	public enum AlgorithmOperationFlags
	{
		XCN_NCRYPT_NO_OPERATION,
		XCN_NCRYPT_CIPHER_OPERATION,
		XCN_NCRYPT_HASH_OPERATION,
		XCN_NCRYPT_ASYMMETRIC_ENCRYPTION_OPERATION = 4,
		XCN_NCRYPT_SECRET_AGREEMENT_OPERATION = 8,
		XCN_NCRYPT_SIGNATURE_OPERATION = 16,
		XCN_NCRYPT_RNG_OPERATION = 32,
		XCN_NCRYPT_ANY_ASYMMETRIC_OPERATION = 28,
		XCN_NCRYPT_PREFER_SIGNATURE_ONLY_OPERATION = 2097152,
		XCN_NCRYPT_PREFER_NON_SIGNATURE_OPERATION = 4194304,
		XCN_NCRYPT_EXACT_MATCH_OPERATION = 8388608,
		XCN_NCRYPT_PREFERENCE_MASK_OPERATION = 14680064
	}
	public enum AlgorithmType
	{
		XCN_BCRYPT_UNKNOWN_INTERFACE,
		XCN_BCRYPT_SIGNATURE_INTERFACE = 5,
		XCN_BCRYPT_ASYMMETRIC_ENCRYPTION_INTERFACE = 3,
		XCN_BCRYPT_CIPHER_INTERFACE = 1,
		XCN_BCRYPT_HASH_INTERFACE,
		XCN_BCRYPT_SECRET_AGREEMENT_INTERFACE = 4,
		XCN_BCRYPT_RNG_INTERFACE = 6
	}
	public enum AlternativeNameType
	{
		XCN_CERT_ALT_NAME_UNKNOWN,
		XCN_CERT_ALT_NAME_OTHER_NAME,
		XCN_CERT_ALT_NAME_RFC822_NAME,
		XCN_CERT_ALT_NAME_DNS_NAME,
		XCN_CERT_ALT_NAME_DIRECTORY_NAME = 5,
		XCN_CERT_ALT_NAME_URL = 7,
		XCN_CERT_ALT_NAME_IP_ADDRESS,
		XCN_CERT_ALT_NAME_REGISTERED_ID,
		XCN_CERT_ALT_NAME_GUID,
		XCN_CERT_ALT_NAME_USER_PRINCIPLE_NAME
	}
	public enum CERTENROLL_OBJECTID
	{
		XCN_OID_NONE,
		XCN_OID_RSA,
		XCN_OID_PKCS,
		XCN_OID_RSA_HASH,
		XCN_OID_RSA_ENCRYPT,
		XCN_OID_PKCS_1,
		XCN_OID_PKCS_2,
		XCN_OID_PKCS_3,
		XCN_OID_PKCS_4,
		XCN_OID_PKCS_5,
		XCN_OID_PKCS_6,
		XCN_OID_PKCS_7,
		XCN_OID_PKCS_8,
		XCN_OID_PKCS_9,
		XCN_OID_PKCS_10,
		XCN_OID_PKCS_12,
		XCN_OID_RSA_RSA,
		XCN_OID_RSA_MD2RSA,
		XCN_OID_RSA_MD4RSA,
		XCN_OID_RSA_MD5RSA,
		XCN_OID_RSA_SHA1RSA,
		XCN_OID_RSA_SETOAEP_RSA,
		XCN_OID_RSA_DH,
		XCN_OID_RSA_data,
		XCN_OID_RSA_signedData,
		XCN_OID_RSA_envelopedData,
		XCN_OID_RSA_signEnvData,
		XCN_OID_RSA_digestedData,
		XCN_OID_RSA_hashedData,
		XCN_OID_RSA_encryptedData,
		XCN_OID_RSA_emailAddr,
		XCN_OID_RSA_unstructName,
		XCN_OID_RSA_contentType,
		XCN_OID_RSA_messageDigest,
		XCN_OID_RSA_signingTime,
		XCN_OID_RSA_counterSign,
		XCN_OID_RSA_challengePwd,
		XCN_OID_RSA_unstructAddr,
		XCN_OID_RSA_extCertAttrs,
		XCN_OID_RSA_certExtensions,
		XCN_OID_RSA_SMIMECapabilities,
		XCN_OID_RSA_preferSignedData,
		XCN_OID_RSA_SMIMEalg,
		XCN_OID_RSA_SMIMEalgESDH,
		XCN_OID_RSA_SMIMEalgCMS3DESwrap,
		XCN_OID_RSA_SMIMEalgCMSRC2wrap,
		XCN_OID_RSA_MD2,
		XCN_OID_RSA_MD4,
		XCN_OID_RSA_MD5,
		XCN_OID_RSA_RC2CBC,
		XCN_OID_RSA_RC4,
		XCN_OID_RSA_DES_EDE3_CBC,
		XCN_OID_RSA_RC5_CBCPad,
		XCN_OID_ANSI_X942,
		XCN_OID_ANSI_X942_DH,
		XCN_OID_X957,
		XCN_OID_X957_DSA,
		XCN_OID_X957_SHA1DSA,
		XCN_OID_DS,
		XCN_OID_DSALG,
		XCN_OID_DSALG_CRPT,
		XCN_OID_DSALG_HASH,
		XCN_OID_DSALG_SIGN,
		XCN_OID_DSALG_RSA,
		XCN_OID_OIW,
		XCN_OID_OIWSEC,
		XCN_OID_OIWSEC_md4RSA,
		XCN_OID_OIWSEC_md5RSA,
		XCN_OID_OIWSEC_md4RSA2,
		XCN_OID_OIWSEC_desECB,
		XCN_OID_OIWSEC_desCBC,
		XCN_OID_OIWSEC_desOFB,
		XCN_OID_OIWSEC_desCFB,
		XCN_OID_OIWSEC_desMAC,
		XCN_OID_OIWSEC_rsaSign,
		XCN_OID_OIWSEC_dsa,
		XCN_OID_OIWSEC_shaDSA,
		XCN_OID_OIWSEC_mdc2RSA,
		XCN_OID_OIWSEC_shaRSA,
		XCN_OID_OIWSEC_dhCommMod,
		XCN_OID_OIWSEC_desEDE,
		XCN_OID_OIWSEC_sha,
		XCN_OID_OIWSEC_mdc2,
		XCN_OID_OIWSEC_dsaComm,
		XCN_OID_OIWSEC_dsaCommSHA,
		XCN_OID_OIWSEC_rsaXchg,
		XCN_OID_OIWSEC_keyHashSeal,
		XCN_OID_OIWSEC_md2RSASign,
		XCN_OID_OIWSEC_md5RSASign,
		XCN_OID_OIWSEC_sha1,
		XCN_OID_OIWSEC_dsaSHA1,
		XCN_OID_OIWSEC_dsaCommSHA1,
		XCN_OID_OIWSEC_sha1RSASign,
		XCN_OID_OIWDIR,
		XCN_OID_OIWDIR_CRPT,
		XCN_OID_OIWDIR_HASH,
		XCN_OID_OIWDIR_SIGN,
		XCN_OID_OIWDIR_md2,
		XCN_OID_OIWDIR_md2RSA,
		XCN_OID_INFOSEC,
		XCN_OID_INFOSEC_sdnsSignature,
		XCN_OID_INFOSEC_mosaicSignature,
		XCN_OID_INFOSEC_sdnsConfidentiality,
		XCN_OID_INFOSEC_mosaicConfidentiality,
		XCN_OID_INFOSEC_sdnsIntegrity,
		XCN_OID_INFOSEC_mosaicIntegrity,
		XCN_OID_INFOSEC_sdnsTokenProtection,
		XCN_OID_INFOSEC_mosaicTokenProtection,
		XCN_OID_INFOSEC_sdnsKeyManagement,
		XCN_OID_INFOSEC_mosaicKeyManagement,
		XCN_OID_INFOSEC_sdnsKMandSig,
		XCN_OID_INFOSEC_mosaicKMandSig,
		XCN_OID_INFOSEC_SuiteASignature,
		XCN_OID_INFOSEC_SuiteAConfidentiality,
		XCN_OID_INFOSEC_SuiteAIntegrity,
		XCN_OID_INFOSEC_SuiteATokenProtection,
		XCN_OID_INFOSEC_SuiteAKeyManagement,
		XCN_OID_INFOSEC_SuiteAKMandSig,
		XCN_OID_INFOSEC_mosaicUpdatedSig,
		XCN_OID_INFOSEC_mosaicKMandUpdSig,
		XCN_OID_INFOSEC_mosaicUpdatedInteg,
		XCN_OID_COMMON_NAME,
		XCN_OID_SUR_NAME,
		XCN_OID_DEVICE_SERIAL_NUMBER,
		XCN_OID_COUNTRY_NAME,
		XCN_OID_LOCALITY_NAME,
		XCN_OID_STATE_OR_PROVINCE_NAME,
		XCN_OID_STREET_ADDRESS,
		XCN_OID_ORGANIZATION_NAME,
		XCN_OID_ORGANIZATIONAL_UNIT_NAME,
		XCN_OID_TITLE,
		XCN_OID_DESCRIPTION,
		XCN_OID_SEARCH_GUIDE,
		XCN_OID_BUSINESS_CATEGORY,
		XCN_OID_POSTAL_ADDRESS,
		XCN_OID_POSTAL_CODE,
		XCN_OID_POST_OFFICE_BOX,
		XCN_OID_PHYSICAL_DELIVERY_OFFICE_NAME,
		XCN_OID_TELEPHONE_NUMBER,
		XCN_OID_TELEX_NUMBER,
		XCN_OID_TELETEXT_TERMINAL_IDENTIFIER,
		XCN_OID_FACSIMILE_TELEPHONE_NUMBER,
		XCN_OID_X21_ADDRESS,
		XCN_OID_INTERNATIONAL_ISDN_NUMBER,
		XCN_OID_REGISTERED_ADDRESS,
		XCN_OID_DESTINATION_INDICATOR,
		XCN_OID_PREFERRED_DELIVERY_METHOD,
		XCN_OID_PRESENTATION_ADDRESS,
		XCN_OID_SUPPORTED_APPLICATION_CONTEXT,
		XCN_OID_MEMBER,
		XCN_OID_OWNER,
		XCN_OID_ROLE_OCCUPANT,
		XCN_OID_SEE_ALSO,
		XCN_OID_USER_PASSWORD,
		XCN_OID_USER_CERTIFICATE,
		XCN_OID_CA_CERTIFICATE,
		XCN_OID_AUTHORITY_REVOCATION_LIST,
		XCN_OID_CERTIFICATE_REVOCATION_LIST,
		XCN_OID_CROSS_CERTIFICATE_PAIR,
		XCN_OID_GIVEN_NAME,
		XCN_OID_INITIALS,
		XCN_OID_DN_QUALIFIER,
		XCN_OID_DOMAIN_COMPONENT,
		XCN_OID_PKCS_12_FRIENDLY_NAME_ATTR,
		XCN_OID_PKCS_12_LOCAL_KEY_ID,
		XCN_OID_PKCS_12_KEY_PROVIDER_NAME_ATTR,
		XCN_OID_LOCAL_MACHINE_KEYSET,
		XCN_OID_PKCS_12_EXTENDED_ATTRIBUTES,
		XCN_OID_KEYID_RDN,
		XCN_OID_AUTHORITY_KEY_IDENTIFIER,
		XCN_OID_KEY_ATTRIBUTES,
		XCN_OID_CERT_POLICIES_95,
		XCN_OID_KEY_USAGE_RESTRICTION,
		XCN_OID_SUBJECT_ALT_NAME,
		XCN_OID_ISSUER_ALT_NAME,
		XCN_OID_BASIC_CONSTRAINTS,
		XCN_OID_KEY_USAGE,
		XCN_OID_PRIVATEKEY_USAGE_PERIOD,
		XCN_OID_BASIC_CONSTRAINTS2,
		XCN_OID_CERT_POLICIES,
		XCN_OID_ANY_CERT_POLICY,
		XCN_OID_AUTHORITY_KEY_IDENTIFIER2,
		XCN_OID_SUBJECT_KEY_IDENTIFIER,
		XCN_OID_SUBJECT_ALT_NAME2,
		XCN_OID_ISSUER_ALT_NAME2,
		XCN_OID_CRL_REASON_CODE,
		XCN_OID_REASON_CODE_HOLD,
		XCN_OID_CRL_DIST_POINTS,
		XCN_OID_ENHANCED_KEY_USAGE,
		XCN_OID_CRL_NUMBER,
		XCN_OID_DELTA_CRL_INDICATOR,
		XCN_OID_ISSUING_DIST_POINT,
		XCN_OID_FRESHEST_CRL,
		XCN_OID_NAME_CONSTRAINTS,
		XCN_OID_POLICY_MAPPINGS,
		XCN_OID_LEGACY_POLICY_MAPPINGS,
		XCN_OID_POLICY_CONSTRAINTS,
		XCN_OID_RENEWAL_CERTIFICATE,
		XCN_OID_ENROLLMENT_NAME_VALUE_PAIR,
		XCN_OID_ENROLLMENT_CSP_PROVIDER,
		XCN_OID_OS_VERSION,
		XCN_OID_ENROLLMENT_AGENT,
		XCN_OID_PKIX,
		XCN_OID_PKIX_PE,
		XCN_OID_AUTHORITY_INFO_ACCESS,
		XCN_OID_BIOMETRIC_EXT,
		XCN_OID_LOGOTYPE_EXT,
		XCN_OID_CERT_EXTENSIONS,
		XCN_OID_NEXT_UPDATE_LOCATION,
		XCN_OID_REMOVE_CERTIFICATE,
		XCN_OID_CROSS_CERT_DIST_POINTS,
		XCN_OID_CTL,
		XCN_OID_SORTED_CTL,
		XCN_OID_SERIALIZED,
		XCN_OID_NT_PRINCIPAL_NAME,
		XCN_OID_PRODUCT_UPDATE,
		XCN_OID_ANY_APPLICATION_POLICY,
		XCN_OID_AUTO_ENROLL_CTL_USAGE,
		XCN_OID_ENROLL_CERTTYPE_EXTENSION,
		XCN_OID_CERT_MANIFOLD,
		XCN_OID_CERTSRV_CA_VERSION,
		XCN_OID_CERTSRV_PREVIOUS_CERT_HASH,
		XCN_OID_CRL_VIRTUAL_BASE,
		XCN_OID_CRL_NEXT_PUBLISH,
		XCN_OID_KP_CA_EXCHANGE,
		XCN_OID_KP_KEY_RECOVERY_AGENT,
		XCN_OID_CERTIFICATE_TEMPLATE,
		XCN_OID_ENTERPRISE_OID_ROOT,
		XCN_OID_RDN_DUMMY_SIGNER,
		XCN_OID_APPLICATION_CERT_POLICIES,
		XCN_OID_APPLICATION_POLICY_MAPPINGS,
		XCN_OID_APPLICATION_POLICY_CONSTRAINTS,
		XCN_OID_ARCHIVED_KEY_ATTR,
		XCN_OID_CRL_SELF_CDP,
		XCN_OID_REQUIRE_CERT_CHAIN_POLICY,
		XCN_OID_ARCHIVED_KEY_CERT_HASH,
		XCN_OID_ISSUED_CERT_HASH,
		XCN_OID_DS_EMAIL_REPLICATION,
		XCN_OID_REQUEST_CLIENT_INFO,
		XCN_OID_ENCRYPTED_KEY_HASH,
		XCN_OID_CERTSRV_CROSSCA_VERSION,
		XCN_OID_NTDS_REPLICATION,
		XCN_OID_SUBJECT_DIR_ATTRS,
		XCN_OID_PKIX_KP,
		XCN_OID_PKIX_KP_SERVER_AUTH,
		XCN_OID_PKIX_KP_CLIENT_AUTH,
		XCN_OID_PKIX_KP_CODE_SIGNING,
		XCN_OID_PKIX_KP_EMAIL_PROTECTION,
		XCN_OID_PKIX_KP_IPSEC_END_SYSTEM,
		XCN_OID_PKIX_KP_IPSEC_TUNNEL,
		XCN_OID_PKIX_KP_IPSEC_USER,
		XCN_OID_PKIX_KP_TIMESTAMP_SIGNING,
		XCN_OID_PKIX_KP_OCSP_SIGNING,
		XCN_OID_PKIX_OCSP_NOCHECK,
		XCN_OID_IPSEC_KP_IKE_INTERMEDIATE,
		XCN_OID_KP_CTL_USAGE_SIGNING,
		XCN_OID_KP_TIME_STAMP_SIGNING,
		XCN_OID_SERVER_GATED_CRYPTO,
		XCN_OID_SGC_NETSCAPE,
		XCN_OID_KP_EFS,
		XCN_OID_EFS_RECOVERY,
		XCN_OID_WHQL_CRYPTO,
		XCN_OID_NT5_CRYPTO,
		XCN_OID_OEM_WHQL_CRYPTO,
		XCN_OID_EMBEDDED_NT_CRYPTO,
		XCN_OID_ROOT_LIST_SIGNER,
		XCN_OID_KP_QUALIFIED_SUBORDINATION,
		XCN_OID_KP_KEY_RECOVERY,
		XCN_OID_KP_DOCUMENT_SIGNING,
		XCN_OID_KP_LIFETIME_SIGNING,
		XCN_OID_KP_MOBILE_DEVICE_SOFTWARE,
		XCN_OID_KP_SMART_DISPLAY,
		XCN_OID_KP_CSP_SIGNATURE,
		XCN_OID_DRM,
		XCN_OID_DRM_INDIVIDUALIZATION,
		XCN_OID_LICENSES,
		XCN_OID_LICENSE_SERVER,
		XCN_OID_KP_SMARTCARD_LOGON,
		XCN_OID_YESNO_TRUST_ATTR,
		XCN_OID_PKIX_POLICY_QUALIFIER_CPS,
		XCN_OID_PKIX_POLICY_QUALIFIER_USERNOTICE,
		XCN_OID_CERT_POLICIES_95_QUALIFIER1,
		XCN_OID_PKIX_ACC_DESCR,
		XCN_OID_PKIX_OCSP,
		XCN_OID_PKIX_CA_ISSUERS,
		XCN_OID_VERISIGN_PRIVATE_6_9,
		XCN_OID_VERISIGN_ONSITE_JURISDICTION_HASH,
		XCN_OID_VERISIGN_BITSTRING_6_13,
		XCN_OID_VERISIGN_ISS_STRONG_CRYPTO,
		XCN_OID_NETSCAPE,
		XCN_OID_NETSCAPE_CERT_EXTENSION,
		XCN_OID_NETSCAPE_CERT_TYPE,
		XCN_OID_NETSCAPE_BASE_URL,
		XCN_OID_NETSCAPE_REVOCATION_URL,
		XCN_OID_NETSCAPE_CA_REVOCATION_URL,
		XCN_OID_NETSCAPE_CERT_RENEWAL_URL,
		XCN_OID_NETSCAPE_CA_POLICY_URL,
		XCN_OID_NETSCAPE_SSL_SERVER_NAME,
		XCN_OID_NETSCAPE_COMMENT,
		XCN_OID_NETSCAPE_DATA_TYPE,
		XCN_OID_NETSCAPE_CERT_SEQUENCE,
		XCN_OID_CT_PKI_DATA,
		XCN_OID_CT_PKI_RESPONSE,
		XCN_OID_PKIX_NO_SIGNATURE,
		XCN_OID_CMC,
		XCN_OID_CMC_STATUS_INFO,
		XCN_OID_CMC_IDENTIFICATION,
		XCN_OID_CMC_IDENTITY_PROOF,
		XCN_OID_CMC_DATA_RETURN,
		XCN_OID_CMC_TRANSACTION_ID,
		XCN_OID_CMC_SENDER_NONCE,
		XCN_OID_CMC_RECIPIENT_NONCE,
		XCN_OID_CMC_ADD_EXTENSIONS,
		XCN_OID_CMC_ENCRYPTED_POP,
		XCN_OID_CMC_DECRYPTED_POP,
		XCN_OID_CMC_LRA_POP_WITNESS,
		XCN_OID_CMC_GET_CERT,
		XCN_OID_CMC_GET_CRL,
		XCN_OID_CMC_REVOKE_REQUEST,
		XCN_OID_CMC_REG_INFO,
		XCN_OID_CMC_RESPONSE_INFO,
		XCN_OID_CMC_QUERY_PENDING,
		XCN_OID_CMC_ID_POP_LINK_RANDOM,
		XCN_OID_CMC_ID_POP_LINK_WITNESS,
		XCN_OID_CMC_ID_CONFIRM_CERT_ACCEPTANCE,
		XCN_OID_CMC_ADD_ATTRIBUTES,
		XCN_OID_LOYALTY_OTHER_LOGOTYPE,
		XCN_OID_BACKGROUND_OTHER_LOGOTYPE,
		XCN_OID_PKIX_OCSP_BASIC_SIGNED_RESPONSE,
		XCN_OID_PKCS_7_DATA,
		XCN_OID_PKCS_7_SIGNED,
		XCN_OID_PKCS_7_ENVELOPED,
		XCN_OID_PKCS_7_SIGNEDANDENVELOPED,
		XCN_OID_PKCS_7_DIGESTED,
		XCN_OID_PKCS_7_ENCRYPTED,
		XCN_OID_PKCS_9_CONTENT_TYPE,
		XCN_OID_PKCS_9_MESSAGE_DIGEST,
		XCN_OID_CERT_PROP_ID_PREFIX,
		XCN_OID_CERT_KEY_IDENTIFIER_PROP_ID,
		XCN_OID_CERT_ISSUER_SERIAL_NUMBER_MD5_HASH_PROP_ID,
		XCN_OID_CERT_SUBJECT_NAME_MD5_HASH_PROP_ID,
		XCN_OID_CERT_MD5_HASH_PROP_ID,
		XCN_OID_RSA_SHA256RSA,
		XCN_OID_RSA_SHA384RSA,
		XCN_OID_RSA_SHA512RSA,
		XCN_OID_NIST_sha256,
		XCN_OID_NIST_sha384,
		XCN_OID_NIST_sha512,
		XCN_OID_RSA_MGF1,
		XCN_OID_ECC_PUBLIC_KEY,
		XCN_OID_RSA_SSA_PSS = 353,
		XCN_OID_ECDSA_SHA1,
		XCN_OID_ECDSA_SPECIFIED = 354
	}
	public enum CERTENROLL_PROPERTYID
	{
		XCN_PROPERTYID_NONE,
		XCN_CERT_KEY_PROV_HANDLE_PROP_ID,
		XCN_CERT_KEY_PROV_INFO_PROP_ID,
		XCN_CERT_SHA1_HASH_PROP_ID,
		XCN_CERT_MD5_HASH_PROP_ID,
		XCN_CERT_HASH_PROP_ID = 3,
		XCN_CERT_KEY_CONTEXT_PROP_ID = 5,
		XCN_CERT_KEY_SPEC_PROP_ID,
		XCN_CERT_IE30_RESERVED_PROP_ID,
		XCN_CERT_PUBKEY_HASH_RESERVED_PROP_ID,
		XCN_CERT_ENHKEY_USAGE_PROP_ID,
		XCN_CERT_CTL_USAGE_PROP_ID = 9,
		XCN_CERT_NEXT_UPDATE_LOCATION_PROP_ID,
		XCN_CERT_FRIENDLY_NAME_PROP_ID,
		XCN_CERT_PVK_FILE_PROP_ID,
		XCN_CERT_DESCRIPTION_PROP_ID,
		XCN_CERT_ACCESS_STATE_PROP_ID,
		XCN_CERT_SIGNATURE_HASH_PROP_ID,
		XCN_CERT_SMART_CARD_DATA_PROP_ID,
		XCN_CERT_EFS_PROP_ID,
		XCN_CERT_FORTEZZA_DATA_PROP_ID,
		XCN_CERT_ARCHIVED_PROP_ID,
		XCN_CERT_KEY_IDENTIFIER_PROP_ID,
		XCN_CERT_AUTO_ENROLL_PROP_ID,
		XCN_CERT_PUBKEY_ALG_PARA_PROP_ID,
		XCN_CERT_CROSS_CERT_DIST_POINTS_PROP_ID,
		XCN_CERT_ISSUER_PUBLIC_KEY_MD5_HASH_PROP_ID,
		XCN_CERT_SUBJECT_PUBLIC_KEY_MD5_HASH_PROP_ID,
		XCN_CERT_ENROLLMENT_PROP_ID,
		XCN_CERT_DATE_STAMP_PROP_ID,
		XCN_CERT_ISSUER_SERIAL_NUMBER_MD5_HASH_PROP_ID,
		XCN_CERT_SUBJECT_NAME_MD5_HASH_PROP_ID,
		XCN_CERT_EXTENDED_ERROR_INFO_PROP_ID,
		XCN_CERT_RENEWAL_PROP_ID = 64,
		XCN_CERT_ARCHIVED_KEY_HASH_PROP_ID,
		XCN_CERT_AUTO_ENROLL_RETRY_PROP_ID,
		XCN_CERT_AIA_URL_RETRIEVED_PROP_ID,
		XCN_CERT_AUTHORITY_INFO_ACCESS_PROP_ID,
		XCN_CERT_BACKED_UP_PROP_ID,
		XCN_CERT_OCSP_RESPONSE_PROP_ID,
		XCN_CERT_REQUEST_ORIGINATOR_PROP_ID,
		XCN_CERT_SOURCE_LOCATION_PROP_ID,
		XCN_CERT_SOURCE_URL_PROP_ID,
		XCN_CERT_NEW_KEY_PROP_ID,
		XCN_CERT_OCSP_CACHE_PREFIX_PROP_ID,
		XCN_CERT_SMART_CARD_ROOT_INFO_PROP_ID,
		XCN_CERT_NO_AUTO_EXPIRE_CHECK_PROP_ID,
		XCN_CERT_NCRYPT_KEY_HANDLE_PROP_ID,
		XCN_CERT_HCRYPTPROV_OR_NCRYPT_KEY_HANDLE_PROP_ID,
		XCN_CERT_SUBJECT_INFO_ACCESS_PROP_ID,
		XCN_CERT_CA_OCSP_AUTHORITY_INFO_ACCESS_PROP_ID,
		XCN_CERT_CA_DISABLE_CRL_PROP_ID,
		XCN_CERT_ROOT_PROGRAM_CERT_POLICIES_PROP_ID,
		XCN_CERT_ROOT_PROGRAM_NAME_CONSTRAINTS_PROP_ID,
		XCN_CERT_SUBJECT_OCSP_AUTHORITY_INFO_ACCESS_PROP_ID,
		XCN_CERT_SUBJECT_DISABLE_CRL_PROP_ID,
		XCN_CERT_CEP_PROP_ID,
		XCN_CERT_SIGN_HASH_CNG_ALG_PROP_ID = 89,
		XCN_CERT_SCARD_PIN_ID_PROP_ID,
		XCN_CERT_SCARD_PIN_INFO_PROP_ID,
		XCN_CERT_SUBJECT_PUB_KEY_BIT_LENGTH_PROP_ID,
		XCN_CERT_PUB_KEY_CNG_ALG_BIT_LENGTH_PROP_ID,
		XCN_CERT_ISSUER_PUB_KEY_BIT_LENGTH_PROP_ID,
		XCN_CERT_ISSUER_CHAIN_SIGN_HASH_CNG_ALG_PROP_ID,
		XCN_CERT_ISSUER_CHAIN_PUB_KEY_CNG_ALG_BIT_LENGTH_PROP_ID,
		XCN_CERT_NO_EXPIRE_NOTIFICATION_PROP_ID,
		XCN_CERT_AUTH_ROOT_SHA256_HASH_PROP_ID,
		XCN_CERT_NCRYPT_KEY_HANDLE_TRANSFER_PROP_ID,
		XCN_CERT_HCRYPTPROV_TRANSFER_PROP_ID,
		XCN_CERT_SMART_CARD_READER_PROP_ID,
		XCN_CERT_SEND_AS_TRUSTED_ISSUER_PROP_ID,
		XCN_CERT_KEY_REPAIR_ATTEMPTED_PROP_ID,
		XCN_CERT_DISALLOWED_FILETIME_PROP_ID,
		XCN_CERT_ROOT_PROGRAM_CHAIN_POLICIES_PROP_ID,
		XCN_CERT_SMART_CARD_READER_NON_REMOVABLE_PROP_ID,
		XCN_CERT_FIRST_RESERVED_PROP_ID,
		XCN_CERT_LAST_RESERVED_PROP_ID = 32767,
		XCN_CERT_FIRST_USER_PROP_ID,
		XCN_CERT_LAST_USER_PROP_ID = 65535,
		XCN_CERT_STORE_LOCALIZED_NAME_PROP_ID = 4096
	}
	public enum CommitTemplateFlags
	{
		CommitFlagSaveTemplateGenerateOID = 1,
		CommitFlagSaveTemplateUseCurrentOID,
		CommitFlagSaveTemplateOverwrite,
		CommitFlagDeleteTemplate
	}
	public enum EncodingType
	{
		XCN_CRYPT_STRING_BASE64HEADER,
		XCN_CRYPT_STRING_BASE64,
		XCN_CRYPT_STRING_BINARY,
		XCN_CRYPT_STRING_BASE64REQUESTHEADER,
		XCN_CRYPT_STRING_HEX,
		XCN_CRYPT_STRING_HEXASCII,
		XCN_CRYPT_STRING_BASE64_ANY,
		XCN_CRYPT_STRING_ANY,
		XCN_CRYPT_STRING_HEX_ANY,
		XCN_CRYPT_STRING_BASE64X509CRLHEADER,
		XCN_CRYPT_STRING_HEXADDR,
		XCN_CRYPT_STRING_HEXASCIIADDR,
		XCN_CRYPT_STRING_HEXRAW,
		XCN_CRYPT_STRING_HASHDATA = 268435456,
		XCN_CRYPT_STRING_STRICT = 536870912,
		XCN_CRYPT_STRING_NOCRLF = 1073741824,
		XCN_CRYPT_STRING_NOCR = -2147483648
	}

	public enum EnrollmentCAProperty
	{
		CAPropCommonName = 1,
		CAPropDistinguishedName,
		CAPropSanitizedName,
		CAPropSanitizedShortName,
		CAPropDNSName,
		CAPropCertificateTypes,
		CAPropCertificate,
		CAPropDescription,
		CAPropWebServers,
		CAPropSiteName,
		CAPropSecurity,
		CAPropRenewalOnly
	}

	public enum EnrollmentDisplayStatus
	{
		DisplayNo,
		DisplayYes
	}
	public enum EnrollmentEnrollStatus
	{
		Enrolled = 1,
		EnrollPended,
		EnrollUIDeferredEnrollmentRequired = 4,
		EnrollError = 16,
		EnrollUnknown = 32,
		EnrollSkipped = 64,
		EnrollDenied = 256
	}
	public enum EnrollmentPolicyServerPropertyFlags
	{
		DefaultNone,
		DefaultPolicyServer
	}
	public enum EnrollmentSelectionStatus
	{
		SelectedNo,
		SelectedYes
	}
	public enum EnrollmentTemplateProperty
	{
		TemplatePropCommonName = 1,
		TemplatePropFriendlyName,
		TemplatePropEKUs,
		TemplatePropCryptoProviders,
		TemplatePropMajorRevision,
		TemplatePropDescription,
		TemplatePropKeySpec,
		TemplatePropSchemaVersion,
		TemplatePropMinorRevision,
		TemplatePropRASignatureCount,
		TemplatePropMinimumKeySize,
		TemplatePropOID,
		TemplatePropSupersede,
		TemplatePropRACertificatePolicies,
		TemplatePropRAEKUs,
		TemplatePropCertificatePolicies,
		TemplatePropV1ApplicationPolicy,
		TemplatePropAsymmetricAlgorithm,
		TemplatePropKeySecurityDescriptor,
		TemplatePropSymmetricAlgorithm,
		TemplatePropSymmetricKeyLength,
		TemplatePropHashAlgorithm,
		TemplatePropKeyUsage,
		TemplatePropEnrollmentFlags,
		TemplatePropSubjectNameFlags,
		TemplatePropPrivateKeyFlags,
		TemplatePropGeneralFlags,
		TemplatePropSecurityDescriptor,
		TemplatePropExtensions,
		TemplatePropValidityPeriod,
		TemplatePropRenewalPeriod
	}
	public enum InnerRequestLevel
	{
		LevelInnermost,
		LevelNext
	}
	public enum InstallResponseRestrictionFlags
	{
		AllowNone,
		AllowNoOutstandingRequest,
		AllowUntrustedCertificate,
		AllowUntrustedRoot = 4
	}
	public enum KeyIdentifierHashAlgorithm
	{
		SKIHashDefault,
		SKIHashSha1,
		SKIHashCapiSha1
	}
	public enum ObjectIdGroupId
	{
		XCN_CRYPT_ANY_GROUP_ID,
		XCN_CRYPT_HASH_ALG_OID_GROUP_ID,
		XCN_CRYPT_ENCRYPT_ALG_OID_GROUP_ID,
		XCN_CRYPT_PUBKEY_ALG_OID_GROUP_ID,
		XCN_CRYPT_SIGN_ALG_OID_GROUP_ID,
		XCN_CRYPT_RDN_ATTR_OID_GROUP_ID,
		XCN_CRYPT_EXT_OR_ATTR_OID_GROUP_ID,
		XCN_CRYPT_ENHKEY_USAGE_OID_GROUP_ID,
		XCN_CRYPT_POLICY_OID_GROUP_ID,
		XCN_CRYPT_TEMPLATE_OID_GROUP_ID,
		XCN_CRYPT_LAST_OID_GROUP_ID,
		XCN_CRYPT_FIRST_ALG_OID_GROUP_ID = 1,
		XCN_CRYPT_LAST_ALG_OID_GROUP_ID = 4,
		XCN_CRYPT_GROUP_ID_MASK = 65535,
		XCN_CRYPT_OID_PREFER_CNG_ALGID_FLAG = 1073741824,
		XCN_CRYPT_OID_DISABLE_SEARCH_DS_FLAG = -2147483648,
		XCN_CRYPT_OID_INFO_OID_GROUP_BIT_LEN_MASK = 268369920,
		XCN_CRYPT_OID_INFO_OID_GROUP_BIT_LEN_SHIFT = 16,
		XCN_CRYPT_KEY_LENGTH_MASK = 268369920
	}
	public enum ObjectIdPublicKeyFlags
	{
		XCN_CRYPT_OID_INFO_PUBKEY_ANY,
		XCN_CRYPT_OID_INFO_PUBKEY_SIGN_KEY_FLAG = -2147483648,
		XCN_CRYPT_OID_INFO_PUBKEY_ENCRYPT_KEY_FLAG = 1073741824
	}
	public enum PFXExportOptions
	{
		PFXExportEEOnly,
		PFXExportChainNoRoot,
		PFXExportChainWithRoot
	}
	public enum Pkcs10AllowedSignatureTypes
	{
		AllowedKeySignature = 1,
		AllowedNullSignature
	}
	public enum PolicyQualifierType
	{
		PolicyQualifierTypeUnknown,
		PolicyQualifierTypeUrl,
		PolicyQualifierTypeUserNotice,
		PolicyQualifierTypeFlags
	}
	public enum PolicyServerUrlFlags
	{
		PsfNone,
		PsfLocationGroupPolicy,
		PsfLocationRegistry,
		PsfUseClientId = 4,
		PsfAutoEnrollmentEnabled = 16,
		PsfAllowUnTrustedCA = 32
	}
	public enum PolicyServerUrlPropertyID
	{
		PsPolicyID,
		PsFriendlyName
	}
	public enum RequestClientInfoClientId
	{
		ClientIdNone,
		ClientIdXEnroll2003,
		ClientIdAutoEnroll2003,
		ClientIdWizard2003,
		ClientIdCertReq2003,
		ClientIdDefaultRequest,
		ClientIdAutoEnroll,
		ClientIdRequestWizard,
		ClientIdEOBO,
		ClientIdCertReq,
		ClientIdTest,
		ClientIdUserStart = 1000
	}
	public enum WebEnrollmentFlags
	{
		EnrollPrompt = 1
	}
	public enum X500NameFlags
	{
		XCN_CERT_NAME_STR_NONE,
		XCN_CERT_SIMPLE_NAME_STR,
		XCN_CERT_OID_NAME_STR,
		XCN_CERT_X500_NAME_STR,
		XCN_CERT_XML_NAME_STR,
		XCN_CERT_NAME_STR_SEMICOLON_FLAG = 1073741824,
		XCN_CERT_NAME_STR_NO_PLUS_FLAG = 536870912,
		XCN_CERT_NAME_STR_NO_QUOTING_FLAG = 268435456,
		XCN_CERT_NAME_STR_CRLF_FLAG = 134217728,
		XCN_CERT_NAME_STR_COMMA_FLAG = 67108864,
		XCN_CERT_NAME_STR_REVERSE_FLAG = 33554432,
		XCN_CERT_NAME_STR_FORWARD_FLAG = 16777216,
		XCN_CERT_NAME_STR_DISABLE_IE4_UTF8_FLAG = 65536,
		XCN_CERT_NAME_STR_ENABLE_T61_UNICODE_FLAG = 131072,
		XCN_CERT_NAME_STR_ENABLE_UTF8_UNICODE_FLAG = 262144,
		XCN_CERT_NAME_STR_FORCE_UTF8_DIR_STR_FLAG = 524288,
		XCN_CERT_NAME_STR_DISABLE_UTF8_DIR_STR_FLAG = 1048576,
		XCN_CERT_NAME_STR_ENABLE_PUNYCODE_FLAG = 2097152
	}
	public enum X509CertificateEnrollmentContext
	{
		ContextUser = 1,
		ContextMachine,
		ContextAdministratorForceMachine
	}
	public enum X509CertificateTemplateEnrollmentFlag
	{
		EnrollmentIncludeSymmetricAlgorithms = 1,
		EnrollmentPendAllRequests,
		EnrollmentPublishToKRAContainer = 4,
		EnrollmentPublishToDS = 8,
		EnrollmentAutoEnrollmentCheckUserDSCertificate = 16,
		EnrollmentAutoEnrollment = 32,
		EnrollmentDomainAuthenticationNotRequired = 128,
		EnrollmentPreviousApprovalValidateReenrollment = 64,
		EnrollmentUserInteractionRequired = 256,
		EnrollmentAddTemplateName = 512,
		EnrollmentRemoveInvalidCertificateFromPersonalStore = 1024,
		EnrollmentAllowEnrollOnBehalfOf = 2048,
		EnrollmentAddOCSPNoCheck = 4096,
		EnrollmentReuseKeyOnFullSmartCard = 8192,
		EnrollmentNoRevocationInfoInCerts = 16384,
		EnrollmentIncludeBasicConstraintsForEECerts = 32768,
		EnrollmentPreviousApprovalKeyBasedValidateReenrollment = 65536,
		EnrollmentCertificateIssuancePoliciesFromRequest = 131072
	}
	public enum X509CertificateTemplateGeneralFlag
	{
		GeneralMachineType = 64,
		GeneralCA = 128,
		GeneralCrossCA = 2048,
		GeneralDefault = 65536,
		GeneralModified = 131072,
		GeneralDonotPersist = 4096
	}
	public enum X509CertificateTemplatePrivateKeyFlag
	{
		PrivateKeyRequireArchival = 1,
		PrivateKeyExportable = 16,
		PrivateKeyRequireStrongKeyProtection = 32,
		PrivateKeyRequireAlternateSignatureAlgorithm = 64,
		PrivateKeyRequireSameKeyRenewal = 128,
		PrivateKeyUseLegacyProvider = 256,
		PrivateKeyServerVersionMask = 983040,
		PrivateKeyServerVersionShift = 16,
		PrivateKeyClientVersionMask = 251658240,
		PrivateKeyClientVersionShift = 24
	}
	public enum X509CertificateTemplateSubjectNameFlag
	{
		SubjectNameEnrolleeSupplies = 1,
		SubjectNameRequireDirectoryPath = -2147483648,
		SubjectNameRequireCommonName = 1073741824,
		SubjectNameRequireEmail = 536870912,
		SubjectNameRequireDNS = 268435456,
		SubjectNameAndAlternativeNameOldCertSupplies = 8,
		SubjectAlternativeNameEnrolleeSupplies = 65536,
		SubjectAlternativeNameRequireDirectoryGUID = 16777216,
		SubjectAlternativeNameRequireUPN = 33554432,
		SubjectAlternativeNameRequireEmail = 67108864,
		SubjectAlternativeNameRequireSPN = 8388608,
		SubjectAlternativeNameRequireDNS = 134217728,
		SubjectAlternativeNameRequireDomainDNS = 4194304
	}
	public enum X509EnrollmentAuthFlags
	{
		X509AuthNone,
		X509AuthAnonymous,
		X509AuthKerberos,
		X509AuthUsername = 4,
		X509AuthCertificate = 8
	}
	public enum X509EnrollmentPolicyExportFlags
	{
		ExportTemplates = 1,
		ExportOIDs,
		ExportCAs = 4
	}
	public enum X509EnrollmentPolicyLoadOption
	{
		LoadOptionDefault,
		LoadOptionCacheOnly,
		LoadOptionReload,
		LoadOptionRegisterForADChanges = 4
	}
	public enum X509KeySpec
	{
		XCN_AT_NONE,
		XCN_AT_KEYEXCHANGE,
		XCN_AT_SIGNATURE
	}
	public enum X509KeyUsageFlags
	{
		XCN_CERT_NO_KEY_USAGE,
		XCN_CERT_DIGITAL_SIGNATURE_KEY_USAGE = 128,
		XCN_CERT_NON_REPUDIATION_KEY_USAGE = 64,
		XCN_CERT_KEY_ENCIPHERMENT_KEY_USAGE = 32,
		XCN_CERT_DATA_ENCIPHERMENT_KEY_USAGE = 16,
		XCN_CERT_KEY_AGREEMENT_KEY_USAGE = 8,
		XCN_CERT_KEY_CERT_SIGN_KEY_USAGE = 4,
		XCN_CERT_OFFLINE_CRL_SIGN_KEY_USAGE = 2,
		XCN_CERT_CRL_SIGN_KEY_USAGE = 2,
		XCN_CERT_ENCIPHER_ONLY_KEY_USAGE = 1,
		XCN_CERT_DECIPHER_ONLY_KEY_USAGE = 32768
	}
	public enum X509PrivateKeyExportFlags
	{
		XCN_NCRYPT_ALLOW_EXPORT_NONE,
		XCN_NCRYPT_ALLOW_EXPORT_FLAG,
		XCN_NCRYPT_ALLOW_PLAINTEXT_EXPORT_FLAG,
		XCN_NCRYPT_ALLOW_ARCHIVING_FLAG = 4,
		XCN_NCRYPT_ALLOW_PLAINTEXT_ARCHIVING_FLAG = 8
	}
	public enum X509PrivateKeyProtection
	{
		XCN_NCRYPT_UI_NO_PROTECTION_FLAG,
		XCN_NCRYPT_UI_PROTECT_KEY_FLAG,
		XCN_NCRYPT_UI_FORCE_HIGH_PROTECTION_FLAG
	}
	public enum X509PrivateKeyUsageFlags
	{
		XCN_NCRYPT_ALLOW_USAGES_NONE,
		XCN_NCRYPT_ALLOW_DECRYPT_FLAG,
		XCN_NCRYPT_ALLOW_SIGNING_FLAG,
		XCN_NCRYPT_ALLOW_KEY_AGREEMENT_FLAG = 4,
		XCN_NCRYPT_ALLOW_ALL_USAGES = 16777215
	}
	public enum X509PrivateKeyVerify
	{
		VerifyNone,
		VerifySilent,
		VerifySmartCardNone,
		VerifySmartCardSilent,
		VerifyAllowUI
	}
	public enum X509ProviderType
	{
		XCN_PROV_NONE,
		XCN_PROV_RSA_FULL,
		XCN_PROV_RSA_SIG,
		XCN_PROV_DSS,
		XCN_PROV_FORTEZZA,
		XCN_PROV_MS_EXCHANGE,
		XCN_PROV_SSL,
		XCN_PROV_RSA_SCHANNEL = 12,
		XCN_PROV_DSS_DH,
		XCN_PROV_EC_ECDSA_SIG,
		XCN_PROV_EC_ECNRA_SIG,
		XCN_PROV_EC_ECDSA_FULL,
		XCN_PROV_EC_ECNRA_FULL,
		XCN_PROV_DH_SCHANNEL,
		XCN_PROV_SPYRUS_LYNKS = 20,
		XCN_PROV_RNG,
		XCN_PROV_INTEL_SEC,
		XCN_PROV_REPLACE_OWF,
		XCN_PROV_RSA_AES
	}
	public enum X509RequestInheritOptions
	{
		InheritDefault,
		InheritNewDefaultKey,
		InheritNewSimilarKey,
		InheritPrivateKey,
		InheritPublicKey,
		InheritKeyMask = 15,
		InheritNone,
		InheritRenewalCertificateFlag = 32,
		InheritTemplateFlag = 64,
		InheritSubjectFlag = 128,
		InheritExtensionsFlag = 256,
		InheritSubjectAltNameFlag = 512,
		InheritValidityPeriodFlag = 1024,
		InheritReserved80000000 = -2147483648
	}
	public enum X509RequestType
	{
		TypeAny,
		TypePkcs10,
		TypePkcs7,
		TypeCmc,
		TypeCertificate
	}

}


"@

Add-Type -TypeDefinition $CERTCLIBSrc
Add-Type -TypeDefinition $CERTENROLLibSrc